name: ci

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build-objects-build-project-build-docker-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    # check for pull_requests:
    if: github.event_name != 'pull_request' || github.event.action == 'closed'
    
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        path: repo
        
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build project with Maven
      working-directory: repo
      run: mvn -B package -DskipTests
    
    - name: Publish jar
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: repo/target/*.jar
